version: "3.1"


services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672